-- Generated by scripts/build-african-company-catalog.mjs. Do not hand edit.
-- Selection provenance: African Business Top 250 Companies 2025, data as of 2025-03-31.
-- This publishes factual source-listed shells only. It does not confer employer verification.
begin;

create temporary table african_company_catalog (
  ranking integer not null,
  slug text not null,
  display_name text not null,
  website_url text not null,
  website_domain text not null,
  industry text not null,
  market_country_code text not null,
  market_country text not null,
  market_region text not null,
  source_url text not null,
  source_title text not null
) on commit drop;

insert into african_company_catalog (
  ranking, slug, display_name, website_url, website_domain, industry,
  market_country_code, market_country, market_region, source_url, source_title
)
values
  (1, 'naspers', 'Naspers', 'https://www.naspers.com/', 'naspers.com', 'Internet software and services', 'ZA', 'South Africa', 'southern_africa', 'https://www.naspers.com/', 'Naspers official website'),
  (2, 'firstrand', 'FirstRand', 'https://www.firstrand.co.za/', 'firstrand.co.za', 'Banking', 'ZA', 'South Africa', 'southern_africa', 'https://www.firstrand.co.za/', 'FirstRand official website'),
  (3, 'standard-bank-group', 'Standard Bank Group', 'https://www.standardbank.com/', 'standardbank.com', 'Banking', 'ZA', 'South Africa', 'southern_africa', 'https://www.standardbank.com/', 'Standard Bank Group official website'),
  (4, 'gold-fields', 'Gold Fields', 'https://www.goldfields.com/', 'goldfields.com', 'Precious metals', 'ZA', 'South Africa', 'southern_africa', 'https://www.goldfields.com/', 'Gold Fields official website'),
  (5, 'capitec-bank', 'Capitec Bank', 'https://www.capitecbank.co.za/', 'capitecbank.co.za', 'Banking', 'ZA', 'South Africa', 'southern_africa', 'https://www.capitecbank.co.za/', 'Capitec Bank official website'),
  (6, 'anglogold-ashanti', 'AngloGold Ashanti', 'https://www.anglogoldashanti.com/', 'anglogoldashanti.com', 'Precious metals', 'ZA', 'South Africa', 'southern_africa', 'https://www.anglogoldashanti.com/', 'AngloGold Ashanti official website'),
  (7, 'attijariwafa-bank', 'Attijariwafa Bank', 'https://www.attijariwafabank.com/', 'attijariwafabank.com', 'Banking', 'MA', 'Morocco', 'north_africa', 'https://www.attijariwafabank.com/', 'Attijariwafa Bank official website'),
  (8, 'vodacom-group', 'Vodacom Group', 'https://www.vodacom.com/', 'vodacom.com', 'Telecommunications', 'ZA', 'South Africa', 'southern_africa', 'https://www.vodacom.com/', 'Vodacom Group official website'),
  (9, 'mtn-group', 'MTN Group', 'https://www.mtn.com/', 'mtn.com', 'Telecommunications', 'ZA', 'South Africa', 'southern_africa', 'https://www.mtn.com/', 'MTN Group official website'),
  (10, 'maroc-telecom', 'Maroc Telecom', 'https://www.iam.ma/', 'iam.ma', 'Telecommunications', 'MA', 'Morocco', 'north_africa', 'https://www.iam.ma/', 'Maroc Telecom official website'),
  (11, 'valterra-platinum', 'Valterra Platinum', 'https://www.valterraplatinum.com/', 'valterraplatinum.com', 'Mining', 'ZA', 'South Africa', 'southern_africa', 'https://www.valterraplatinum.com/', 'Valterra Platinum official website'),
  (12, 'sanlam', 'Sanlam', 'https://www.sanlam.com/', 'sanlam.com', 'Insurance', 'ZA', 'South Africa', 'southern_africa', 'https://www.sanlam.com/', 'Sanlam official website'),
  (13, 'harmony-gold-mining', 'Harmony Gold Mining', 'https://www.harmony.co.za/', 'harmony.co.za', 'Precious metals', 'ZA', 'South Africa', 'southern_africa', 'https://www.harmony.co.za/', 'Harmony Gold Mining official website'),
  (14, 'shoprite-holdings', 'Shoprite Holdings', 'https://www.shopriteholdings.co.za/', 'shopriteholdings.co.za', 'Food retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.shopriteholdings.co.za/', 'Shoprite Holdings official website'),
  (15, 'absa-group', 'Absa Group', 'https://www.absa.africa/', 'absa.africa', 'Banking', 'ZA', 'South Africa', 'southern_africa', 'https://www.absa.africa/', 'Absa Group official website'),
  (16, 'bidcorp', 'Bidcorp', 'https://www.bidcorpgroup.com/', 'bidcorpgroup.com', 'Food services', 'ZA', 'South Africa', 'southern_africa', 'https://www.bidcorpgroup.com/', 'Bidcorp official website'),
  (17, 'airtel-africa', 'Airtel Africa', 'https://www.airtel.africa/', 'airtel.africa', 'Telecommunications', 'NG', 'Nigeria', 'west_africa', 'https://www.airtel.africa/', 'Airtel Africa official website'),
  (18, 'discovery-limited', 'Discovery Limited', 'https://www.discovery.co.za/', 'discovery.co.za', 'Insurance', 'ZA', 'South Africa', 'southern_africa', 'https://www.discovery.co.za/', 'Discovery official website'),
  (19, 'nedbank-group', 'Nedbank Group', 'https://www.nedbank.co.za/', 'nedbank.co.za', 'Banking', 'ZA', 'South Africa', 'southern_africa', 'https://www.nedbank.co.za/', 'Nedbank Group official website'),
  (20, 'impala-platinum', 'Impala Platinum', 'https://www.implats.co.za/', 'implats.co.za', 'Mining', 'ZA', 'South Africa', 'southern_africa', 'https://www.implats.co.za/', 'Impala Platinum official website'),
  (21, 'managem', 'Managem', 'https://www.managemgroup.com/', 'managemgroup.com', 'Mining', 'MA', 'Morocco', 'north_africa', 'https://www.managemgroup.com/', 'Managem official website'),
  (22, 'banque-centrale-populaire', 'Banque Centrale Populaire', 'https://www.groupebcp.com/', 'groupebcp.com', 'Banking', 'MA', 'Morocco', 'north_africa', 'https://www.groupebcp.com/', 'Groupe BCP official website'),
  (23, 'outsurance-group', 'OUTsurance Group', 'https://www.outsurancegroup.co.za/', 'outsurancegroup.co.za', 'Insurance', 'ZA', 'South Africa', 'southern_africa', 'https://www.outsurancegroup.co.za/', 'OUTsurance Group official website'),
  (24, 'marsa-maroc', 'Marsa Maroc', 'https://www.marsamaroc.co.ma/', 'marsamaroc.co.ma', 'Transportation', 'MA', 'Morocco', 'north_africa', 'https://www.marsamaroc.co.ma/', 'Marsa Maroc official website'),
  (25, 'safaricom', 'Safaricom', 'https://www.safaricom.co.ke/', 'safaricom.co.ke', 'Telecommunications', 'KE', 'Kenya', 'east_africa', 'https://www.safaricom.co.ke/', 'Safaricom official website'),
  (26, 'taqa-morocco', 'TAQA Morocco', 'https://www.taqamorocco.ma/', 'taqamorocco.ma', 'Electric utilities', 'MA', 'Morocco', 'north_africa', 'https://www.taqamorocco.ma/', 'TAQA Morocco official website'),
  (27, 'kumba-iron-ore', 'Kumba Iron Ore', 'https://www.angloamericankumba.com/', 'angloamericankumba.com', 'Mining', 'ZA', 'South Africa', 'southern_africa', 'https://www.angloamericankumba.com/', 'Kumba Iron Ore official website'),
  (28, 'dangote-cement', 'Dangote Cement', 'https://www.dangotecement.com/', 'dangotecement.com', 'Construction materials', 'NG', 'Nigeria', 'west_africa', 'https://www.dangotecement.com/', 'Dangote Cement official website'),
  (29, 'pepkor-holdings', 'Pepkor Holdings', 'https://www.pepkor.co.za/', 'pepkor.co.za', 'Retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.pepkor.co.za/', 'Pepkor Holdings official website'),
  (30, 'commercial-international-bank-egypt', 'Commercial International Bank Egypt', 'https://www.cibeg.com/', 'cibeg.com', 'Banking', 'EG', 'Egypt', 'north_africa', 'https://www.cibeg.com/', 'Commercial International Bank Egypt official website'),
  (31, 'bua-foods', 'BUA Foods', 'https://www.buafoodsplc.com/', 'buafoodsplc.com', 'Food production', 'NG', 'Nigeria', 'west_africa', 'https://www.buafoodsplc.com/', 'BUA Foods official website'),
  (32, 'reinet-investments', 'Reinet Investments', 'https://www.reinet.com/', 'reinet.com', 'Investment management', 'ZA', 'South Africa', 'southern_africa', 'https://www.reinet.com/', 'Reinet Investments official website'),
  (33, 'lafargeholcim-maroc', 'LafargeHolcim Maroc', 'https://www.lafargeholcim.ma/', 'lafargeholcim.ma', 'Construction materials', 'MA', 'Morocco', 'north_africa', 'https://www.lafargeholcim.ma/', 'LafargeHolcim Maroc official website'),
  (34, 'remgro', 'Remgro', 'https://www.remgro.com/', 'remgro.com', 'Diversified investments', 'ZA', 'South Africa', 'southern_africa', 'https://www.remgro.com/', 'Remgro official website'),
  (35, 'bank-of-africa-morocco', 'Bank of Africa Morocco', 'https://www.bankofafrica.ma/', 'bankofafrica.ma', 'Banking', 'MA', 'Morocco', 'north_africa', 'https://www.bankofafrica.ma/', 'Bank of Africa Morocco official website'),
  (36, 'clicks-group', 'Clicks Group', 'https://www.clicksgroup.co.za/', 'clicksgroup.co.za', 'Health and beauty retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.clicksgroup.co.za/', 'Clicks Group official website'),
  (37, 'bidvest-group', 'Bidvest Group', 'https://www.bidvest.co.za/', 'bidvest.co.za', 'Diversified services', 'ZA', 'South Africa', 'southern_africa', 'https://www.bidvest.co.za/', 'Bidvest Group official website'),
  (38, 'sonatel', 'Sonatel', 'https://www.sonatel.sn/', 'sonatel.sn', 'Telecommunications', 'SN', 'Senegal', 'west_africa', 'https://www.sonatel.sn/', 'Sonatel official website'),
  (39, 'aspen-pharmacare', 'Aspen Pharmacare', 'https://www.aspenpharma.com/', 'aspenpharma.com', 'Pharmaceuticals', 'ZA', 'South Africa', 'southern_africa', 'https://www.aspenpharma.com/', 'Aspen Pharmacare official website'),
  (40, 'b2gold', 'B2Gold', 'https://www.b2gold.com/', 'b2gold.com', 'Mining', 'NA', 'Namibia', 'southern_africa', 'https://www.b2gold.com/', 'B2Gold official website'),
  (41, 'orange-cote-divoire', 'Orange Côte d’Ivoire', 'https://www.orange.ci/', 'orange.ci', 'Telecommunications', 'CI', 'Côte d’Ivoire', 'west_africa', 'https://www.orange.ci/', 'Orange Côte d’Ivoire official website'),
  (42, 'elsewedy-electric', 'Elsewedy Electric', 'https://www.elsewedyelectric.com/', 'elsewedyelectric.com', 'Electrical products', 'EG', 'Egypt', 'north_africa', 'https://www.elsewedyelectric.com/', 'Elsewedy Electric official website'),
  (43, 'mtn-nigeria', 'MTN Nigeria', 'https://www.mtn.ng/', 'mtn.ng', 'Telecommunications', 'NG', 'Nigeria', 'west_africa', 'https://www.mtn.ng/', 'MTN Nigeria official website'),
  (44, 'sibanye-stillwater', 'Sibanye-Stillwater', 'https://www.sibanyestillwater.com/', 'sibanyestillwater.com', 'Precious metals', 'ZA', 'South Africa', 'southern_africa', 'https://www.sibanyestillwater.com/', 'Sibanye-Stillwater official website'),
  (45, 'mr-price-group', 'Mr Price Group', 'https://www.mrpricegroup.com/', 'mrpricegroup.com', 'Retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.mrpricegroup.com/', 'Mr Price Group official website'),
  (46, 'old-mutual', 'Old Mutual', 'https://www.oldmutual.com/', 'oldmutual.com', 'Insurance', 'ZA', 'South Africa', 'southern_africa', 'https://www.oldmutual.com/', 'Old Mutual official website'),
  (47, 'ciments-du-maroc', 'Ciments du Maroc', 'https://www.cimentsdumaroc.com/', 'cimentsdumaroc.com', 'Construction materials', 'MA', 'Morocco', 'north_africa', 'https://www.cimentsdumaroc.com/', 'Ciments du Maroc official website'),
  (48, 'northam-platinum', 'Northam Platinum', 'https://www.northam.co.za/', 'northam.co.za', 'Mining', 'ZA', 'South Africa', 'southern_africa', 'https://www.northam.co.za/', 'Northam Platinum official website'),
  (49, 'exxaro-resources', 'Exxaro Resources', 'https://www.exxaro.com/', 'exxaro.com', 'Mining', 'ZA', 'South Africa', 'southern_africa', 'https://www.exxaro.com/', 'Exxaro Resources official website'),
  (50, 'woolworths-holdings', 'Woolworths Holdings', 'https://www.woolworthsholdings.co.za/', 'woolworthsholdings.co.za', 'Retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.woolworthsholdings.co.za/', 'Woolworths Holdings official website'),
  (51, 'tiger-brands', 'Tiger Brands', 'https://www.tigerbrands.com/', 'tigerbrands.com', 'Food production', 'ZA', 'South Africa', 'southern_africa', 'https://www.tigerbrands.com/', 'Tiger Brands official website'),
  (52, 'mtn-ghana-scancom', 'MTN Ghana (Scancom)', 'https://mtn.com.gh/', 'mtn.com.gh', 'Telecommunications', 'GH', 'Ghana', 'west_africa', 'https://mtn.com.gh/', 'MTN Ghana official website'),
  (53, 'mcb-group', 'MCB Group', 'https://mcbgroup.com/', 'mcbgroup.com', 'Banking', 'MU', 'Mauritius', 'east_africa', 'https://mcbgroup.com/', 'MCB Group official website'),
  (54, 'sasol', 'Sasol', 'https://www.sasol.com/', 'sasol.com', 'Chemicals and energy', 'ZA', 'South Africa', 'southern_africa', 'https://www.sasol.com/', 'Sasol official website'),
  (55, 'multichoice-group', 'MultiChoice Group', 'https://www.multichoice.com/', 'multichoice.com', 'Media', 'ZA', 'South Africa', 'southern_africa', 'https://www.multichoice.com/', 'MultiChoice Group official website'),
  (56, 'truworths-zimbabwe', 'Truworths Zimbabwe', 'https://www.truworths.co.zw/', 'truworths.co.zw', 'Retail', 'ZW', 'Zimbabwe', 'southern_africa', 'https://www.truworths.co.zw/', 'Truworths Zimbabwe official website'),
  (57, 'santam', 'Santam', 'https://www.santam.co.za/', 'santam.co.za', 'Insurance', 'ZA', 'South Africa', 'southern_africa', 'https://www.santam.co.za/', 'Santam official website'),
  (58, 'momentum-metropolitan', 'Momentum Metropolitan', 'https://www.momentummetropolitan.co.za/', 'momentummetropolitan.co.za', 'Insurance', 'ZA', 'South Africa', 'southern_africa', 'https://www.momentummetropolitan.co.za/', 'Momentum Metropolitan official website'),
  (59, 'tgcc', 'TGCC', 'https://tgcc.ma/', 'tgcc.ma', 'Engineering and construction', 'MA', 'Morocco', 'north_africa', 'https://tgcc.ma/', 'TGCC official website'),
  (60, 'foschini-group', 'The Foschini Group', 'https://tfglimited.co.za/', 'tfglimited.co.za', 'Retail', 'ZA', 'South Africa', 'southern_africa', 'https://tfglimited.co.za/', 'The Foschini Group official website'),
  (61, 'cosumar', 'Cosumar', 'https://www.cosumar.co.ma/', 'cosumar.co.ma', 'Food production', 'MA', 'Morocco', 'north_africa', 'https://www.cosumar.co.ma/', 'Cosumar official website'),
  (62, 'talaat-moustafa-group', 'Talaat Moustafa Group', 'https://talaatmoustafa.com/', 'talaatmoustafa.com', 'Real estate development', 'EG', 'Egypt', 'north_africa', 'https://talaatmoustafa.com/', 'Talaat Moustafa Group official website'),
  (63, 'eastern-company', 'Eastern Company', 'https://www.easternegypt.com/', 'easternegypt.com', 'Tobacco', 'EG', 'Egypt', 'north_africa', 'https://www.easternegypt.com/', 'Eastern Company official website'),
  (64, 'fmb-capital-holdings', 'FMB Capital Holdings', 'https://www.fmbcapitalgroup.com/', 'fmbcapitalgroup.com', 'Banking', 'MW', 'Malawi', 'southern_africa', 'https://www.fmbcapitalgroup.com/', 'FMB Capital Holdings official website'),
  (65, 'groupe-addoha', 'Groupe Addoha', 'https://www.groupeaddoha.com/', 'groupeaddoha.com', 'Real estate development', 'MA', 'Morocco', 'north_africa', 'https://www.groupeaddoha.com/', 'Groupe Addoha official website'),
  (66, 'akdital', 'Akdital', 'https://akdital.ma/', 'akdital.ma', 'Healthcare', 'MA', 'Morocco', 'north_africa', 'https://akdital.ma/', 'Akdital official website'),
  (67, 'geregu-power', 'Geregu Power', 'https://www.geregupowerplc.com/', 'geregupowerplc.com', 'Electric utilities', 'NG', 'Nigeria', 'west_africa', 'https://www.geregupowerplc.com/', 'Geregu Power official website'),
  (68, 'wafa-assurance', 'Wafa Assurance', 'https://www.wafaassurance.ma/', 'wafaassurance.ma', 'Insurance', 'MA', 'Morocco', 'north_africa', 'https://www.wafaassurance.ma/', 'Wafa Assurance official website'),
  (69, 'bua-cement', 'BUA Cement', 'https://www.buacement.com/', 'buacement.com', 'Construction materials', 'NG', 'Nigeria', 'west_africa', 'https://www.buacement.com/', 'BUA Cement official website'),
  (70, 'investec', 'Investec', 'https://www.investec.com/', 'investec.com', 'Financial services', 'ZA', 'South Africa', 'southern_africa', 'https://www.investec.com/', 'Investec official website'),
  (71, 'transcorp-power', 'Transcorp Power', 'https://transcorppower.com/', 'transcorppower.com', 'Electric utilities', 'NG', 'Nigeria', 'west_africa', 'https://transcorppower.com/', 'Transcorp Power official website'),
  (72, 'african-rainbow-minerals', 'African Rainbow Minerals', 'https://www.arm.co.za/', 'arm.co.za', 'Mining', 'ZA', 'South Africa', 'southern_africa', 'https://www.arm.co.za/', 'African Rainbow Minerals official website'),
  (73, 'boxer-retail', 'Boxer Retail', 'https://www.boxer.co.za/', 'boxer.co.za', 'Food retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.boxer.co.za/', 'Boxer Retail official website'),
  (74, 'totalenergies-marketing-maroc', 'TotalEnergies Marketing Maroc', 'https://totalenergies.ma/', 'totalenergies.ma', 'Energy retail', 'MA', 'Morocco', 'north_africa', 'https://totalenergies.ma/', 'TotalEnergies Marketing Maroc official website'),
  (75, 'mopco', 'MOPCO', 'https://www.mopco-eg.com/', 'mopco-eg.com', 'Agricultural chemicals', 'EG', 'Egypt', 'north_africa', 'https://www.mopco-eg.com/', 'MOPCO official website'),
  (76, 'national-bank-of-malawi', 'National Bank of Malawi', 'https://www.natbank.co.mw/', 'natbank.co.mw', 'Banking', 'MW', 'Malawi', 'southern_africa', 'https://www.natbank.co.mw/', 'National Bank of Malawi official website'),
  (77, 'mtn-uganda', 'MTN Uganda', 'https://www.mtn.co.ug/', 'mtn.co.ug', 'Telecommunications', 'UG', 'Uganda', 'east_africa', 'https://www.mtn.co.ug/', 'MTN Uganda official website'),
  (78, 'getbucks-microfinance-bank', 'GetBucks Microfinance Bank', 'https://getbucks.co.zw/', 'getbucks.co.zw', 'Financial services', 'ZW', 'Zimbabwe', 'southern_africa', 'https://getbucks.co.zw/', 'GetBucks Microfinance Bank official website'),
  (79, 'avi-limited', 'AVI Limited', 'https://www.avi.co.za/', 'avi.co.za', 'Consumer goods', 'ZA', 'South Africa', 'southern_africa', 'https://www.avi.co.za/', 'AVI Limited official website'),
  (80, 'truworths-international', 'Truworths International', 'https://www.truworthsinternational.com/', 'truworthsinternational.com', 'Retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.truworthsinternational.com/', 'Truworths International official website'),
  (81, 'afriquia-gaz', 'Afriquia Gaz', 'https://www.afriquiagaz.com/', 'afriquiagaz.com', 'Energy distribution', 'MA', 'Morocco', 'north_africa', 'https://www.afriquiagaz.com/', 'Afriquia Gaz official website'),
  (82, 'guaranty-trust-holding-company', 'Guaranty Trust Holding Company', 'https://www.gtcoplc.com/', 'gtcoplc.com', 'Banking', 'NG', 'Nigeria', 'west_africa', 'https://www.gtcoplc.com/', 'Guaranty Trust Holding Company official website'),
  (83, 'ezz-steel', 'Ezz Steel', 'https://www.ezzsteel.com/', 'ezzsteel.com', 'Steel', 'EG', 'Egypt', 'north_africa', 'https://www.ezzsteel.com/', 'Ezz Steel official website'),
  (84, 'egypt-aluminum', 'Egypt Aluminum', 'https://www.egyptalum.com.eg/', 'egyptalum.com.eg', 'Aluminum', 'EG', 'Egypt', 'north_africa', 'https://www.egyptalum.com.eg/', 'Egypt Aluminum official website'),
  (85, 'abou-kir-fertilizers', 'Abou Kir Fertilizers', 'https://www.abuqir.net/', 'abuqir.net', 'Agricultural chemicals', 'EG', 'Egypt', 'north_africa', 'https://www.abuqir.net/', 'Abou Kir Fertilizers official website'),
  (86, 'dis-chem-pharmacies', 'Dis-Chem Pharmacies', 'https://www.dischem.co.za/', 'dischem.co.za', 'Health and beauty retail', 'ZA', 'South Africa', 'southern_africa', 'https://www.dischem.co.za/', 'Dis-Chem Pharmacies official website'),
  (87, 'aradel-holdings', 'Aradel Holdings', 'https://www.aradel.com/', 'aradel.com', 'Energy', 'NG', 'Nigeria', 'west_africa', 'https://www.aradel.com/', 'Aradel Holdings official website'),
  (88, 'equity-group-holdings', 'Equity Group Holdings', 'https://equitygroupholdings.com/', 'equitygroupholdings.com', 'Banking', 'KE', 'Kenya', 'east_africa', 'https://equitygroupholdings.com/', 'Equity Group Holdings official website'),
  (89, 'cih-bank', 'CIH Bank', 'https://www.cihbank.ma/', 'cihbank.ma', 'Banking', 'MA', 'Morocco', 'north_africa', 'https://www.cihbank.ma/', 'CIH Bank official website'),
  (90, 'drdgold', 'DRDGOLD', 'https://www.drdgold.com/', 'drdgold.com', 'Precious metals', 'ZA', 'South Africa', 'southern_africa', 'https://www.drdgold.com/', 'DRDGOLD official website'),
  (91, 'labelvie', 'LabelVie', 'https://www.labelvie.ma/', 'labelvie.ma', 'Food retail', 'MA', 'Morocco', 'north_africa', 'https://www.labelvie.ma/', 'LabelVie official website'),
  (92, 'credit-du-maroc', 'Crédit du Maroc', 'https://www.creditdumaroc.ma/', 'creditdumaroc.ma', 'Banking', 'MA', 'Morocco', 'north_africa', 'https://www.creditdumaroc.ma/', 'Crédit du Maroc official website'),
  (93, 'karooooo', 'Karooooo', 'https://www.karooooo.com/', 'karooooo.com', 'Internet software and services', 'ZA', 'South Africa', 'southern_africa', 'https://www.karooooo.com/', 'Karooooo official website'),
  (94, 'biat', 'BIAT', 'https://www.biat.com.tn/', 'biat.com.tn', 'Banking', 'TN', 'Tunisia', 'north_africa', 'https://www.biat.com.tn/', 'BIAT official website'),
  (95, 'qnb-egypt', 'QNB Egypt', 'https://www.qnbalahli.com/', 'qnbalahli.com', 'Banking', 'EG', 'Egypt', 'north_africa', 'https://www.qnbalahli.com/', 'QNB Egypt official website'),
  (96, 'alliances-developpement-immobilier', 'Alliances Développement Immobilier', 'https://www.alliances.co.ma/', 'alliances.co.ma', 'Real estate development', 'MA', 'Morocco', 'north_africa', 'https://www.alliances.co.ma/', 'Alliances Développement Immobilier official website'),
  (97, 'zenith-bank', 'Zenith Bank', 'https://www.zenithbank.com/', 'zenithbank.com', 'Banking', 'NG', 'Nigeria', 'west_africa', 'https://www.zenithbank.com/', 'Zenith Bank official website'),
  (98, 'fdh-bank', 'FDH Bank', 'https://www.fdh.co.mw/', 'fdh.co.mw', 'Banking', 'MW', 'Malawi', 'southern_africa', 'https://www.fdh.co.mw/', 'FDH Bank official website'),
  (99, 'alexandria-container-and-cargo-handling', 'Alexandria Container and Cargo Handling', 'https://www.alexcont.com/', 'alexcont.com', 'Transportation', 'EG', 'Egypt', 'north_africa', 'https://www.alexcont.com/', 'Alexandria Container and Cargo Handling official website'),
  (100, 'spar-group', 'The SPAR Group', 'https://thespargroup.com/', 'thespargroup.com', 'Wholesale distribution', 'ZA', 'South Africa', 'southern_africa', 'https://thespargroup.com/', 'The SPAR Group official website');

do $$
declare
  collision record;
begin
  select catalog.slug as incoming_slug, existing.slug as existing_slug,
         catalog.website_domain
  into collision
  from african_company_catalog catalog
  join app.companies existing
    on existing.website_domain = catalog.website_domain
   and existing.slug <> catalog.slug
  limit 1;

  if found then
    raise exception 'African company catalog domain collision: % belongs to existing slug %, incoming slug %',
      collision.website_domain, collision.existing_slug, collision.incoming_slug;
  end if;
end;
$$;

insert into app.companies (
  slug, display_name, website_url, website_domain, industry,
  verification_status, verification_scope, record_status
)
select
  slug, display_name, website_url, website_domain, industry,
  'unverified',
  'Official website and domain are source-listed; employer identity is not verified',
  'published'
from african_company_catalog
on conflict (slug) do update
set display_name = case
      when app.companies.verification_status = 'unverified' then excluded.display_name
      else app.companies.display_name
    end,
    website_url = coalesce(app.companies.website_url, excluded.website_url),
    website_domain = coalesce(app.companies.website_domain, excluded.website_domain),
    industry = coalesce(app.companies.industry, excluded.industry),
    verification_scope = case
      when app.companies.verification_status = 'unverified' then excluded.verification_scope
      else app.companies.verification_scope
    end,
    record_status = case
      when app.companies.verification_status = 'unverified'
       and app.companies.record_status in ('draft', 'pending', 'published')
        then 'published'::app.record_status
      else app.companies.record_status
    end,
    updated_at = clock_timestamp();

insert into app.company_fact_citations (
  company_id, fact_key, fact_value, source_kind, source_url, source_title,
  retrieved_at, fact_checked_at, review_due_at, status
)
select
  company.id,
  fact.fact_key,
  fact.fact_value,
  'official_site',
  catalog.source_url,
  catalog.source_title,
  '2026-07-14T00:00:00.000Z'::timestamptz,
  '2026-07-14T00:00:00.000Z'::timestamptz,
  '2027-01-14T00:00:00.000Z'::timestamptz,
  'current'
from african_company_catalog catalog
join app.companies company on company.slug = catalog.slug
cross join lateral (
  values
    ('brand_name', jsonb_build_object('value', catalog.display_name)),
    ('website', jsonb_build_object('value', catalog.website_url)),
    ('official_domain', jsonb_build_object('value', catalog.website_domain)),
    ('industry', jsonb_build_object('value', catalog.industry))
) as fact(fact_key, fact_value)
on conflict (company_id, fact_key, source_url) do update
set fact_value = excluded.fact_value,
    source_title = excluded.source_title,
    retrieved_at = excluded.retrieved_at,
    fact_checked_at = excluded.fact_checked_at,
    review_due_at = excluded.review_due_at,
    status = 'current',
    updated_at = clock_timestamp();

insert into app.company_domains (
  company_id, domain, domain_kind, is_official, citation_id,
  verified_at, review_due_at
)
select
  company.id,
  catalog.website_domain,
  'corporate',
  true,
  citation.id,
  citation.fact_checked_at,
  citation.review_due_at
from african_company_catalog catalog
join app.companies company on company.slug = catalog.slug
join app.company_fact_citations citation
  on citation.company_id = company.id
 and citation.fact_key = 'official_domain'
 and citation.source_url = catalog.source_url
on conflict (domain) do update
set citation_id = excluded.citation_id,
    verified_at = excluded.verified_at,
    review_due_at = excluded.review_due_at;

commit;
